name: 03 Delete Specified Folder

on:
  workflow_dispatch:
    inputs:
      folder_names:
        description: 'Names of the folders to delete (comma-separated)'
        required: true
        default: '2024_0301,2024_0302'

jobs:
  delete_specified_folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Delete specified folders
      run: |
        IFS=',' read -ra folder_names <<< "${{ github.event.inputs.folder_names }}"
        echo "Folders to delete: ${folder_names[@]}"

        for folder_name in "${folder_names[@]}"; do
          folder_name=$(echo "$folder_name" | xargs)
          echo "Processing folder: $folder_name"  # 追加: 処理中のフォルダ名を表示
          if [[ -d "$folder_name" ]]; then
            rm -rf "$folder_name"
            echo "Deleted folder: $folder_name"
          else
            echo "Folder not found: $folder_name"
          fi
        done
