name: 03 Bulk Folder Deletion

on:
  workflow_dispatch:
    inputs:
      folders_to_delete:
        description: 'Folders to delete (comma-separated)'
        required: true
        default: ''

jobs:
  bulk_folder_deletion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Delete specified folders
      run: |
        folders="${{ github.event.inputs.folders_to_delete }}"
        IFS=',' read -ra folder_array <<< "$folders"
        for folder in "${folder_array[@]}"; do
          if [ -d "$folder" ]; then
            rm -rf "$folder"
            echo "Deleted folder: $folder"
          else
            echo "Folder not found: $folder"
          fi
        done
