name: 03 Delete Old Folders

on:
  workflow_dispatch:
    inputs:
      cutoff_days:
        description: 'Number of days to keep folders'
        required: true
        default: '30'

jobs:
  delete_old_folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Delete old folders
      run: |
        cutoff_date=$(date -d "${{ github.event.inputs.cutoff_days }} days ago" +%Y-%m-%d)
        echo "Cutoff date: $cutoff_date"

        for folder in */; do
          if [[ -d "$folder" ]]; then
            folder_date=$(echo "$folder" | grep -oE '[0-9]{4}_[0-9]{4}' | sed 's/_/-/')
            if [[ -n "$folder_date" && "$folder_date" < "$cutoff_date" ]]; then
              rm -rf "$folder"
              echo "Deleted folder: $folder"
            else
              echo "Skipping folder: $folder"
            fi
          fi
        done
