name: 03 Delete Folders

on:
  workflow_dispatch:

jobs:
  delete_folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete folders
      run: |
        rm -rf y_body/2024_0216 y_body/2024_0217
        echo "Deleted folders"
