name: 03 Delete Specified Folder

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Name of the folder to delete'
        required: true
        default: '2024_0301'

jobs:
  delete_specified_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Log start of workflow
      run: echo "Start of workflow"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Check if folder exists
      run: |
        folder_name="${{ github.event.inputs.folder_name }}"
        echo "Folder to check: $folder_name"
        if [[ -d "$folder_name" ]]; then
          echo "Folder exists: $folder_name"
        else
          echo "Folder not found: $folder_name"
        fi

    - name: Log before delete specified folder
      run: echo "Before deleting specified folder"

    - name: Delete specified folder
      run: |
        folder_name="${{ github.event.inputs.folder_name }}"
        echo "Folder to delete: $folder_name"

        if [[ -d "$folder_name" ]]; then
          rm -rf "$folder_name"
          echo "Deleted folder: $folder_name"
        else
          echo "Folder not found: $folder_name"
        fi

    - name: Log end of workflow
      run: echo "End of workflow"
