name: 04 Delete Repositories

on:
  workflow_dispatch:

jobs:
  delete_repositories:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read delete_target.txt file and delete repositories
      run: |
        while IFS= read -r line; do
          reponame="${line%%[[:space:]]}"
          gh repo delete "$reponame" --yes
          echo "Deleted $reponame"
        done < <(tr -d '\r' < delete_target.txt)
