name: Schedule g01

on:
  schedule:
    - cron: '0 16 * * *'  # UTC時間の16:00に実行（日本時間の午前1時）
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # 最新バージョンに更新
      - uses: actions/setup-python@v3  # 最新バージョンに更新
        with:
          python-version: '3.8'
          
      - name: Create directory for the previous day
        run: |
          current_date=$(date +'%Y_%m%d') 
          yesterday=$(date -d "yesterday" +'%Y_%m%d')
          folder_name="${yesterday}"
          mkdir -p $folder_name

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4 pytz boto3
      
      - name: Run scraper
        run: python py/file-g01.py

      - name: Set Git Config
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
        working-directory: ${{ github.workspace }}

      - name: Pull remote changes
        run: git pull origin main
        working-directory: ${{ github.workspace }}

      - name: Commit and push csv files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update csv files - $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
        working-directory: ${{ github.workspace }}
